"""
Lee's Stock Portfolio Bot — Discord
Posts AI-selected stock portfolio picks with bull/bear thesis
"""

import discord
from discord.ext import commands, tasks
import anthropic
import os
import json
import asyncio
from datetime import datetime, time
from dotenv import load_dotenv
from stock_engine import build_portfolio

load_dotenv()

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
CHANNEL_ID = int(os.getenv("DISCORD_CHANNEL_ID", "0"))
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

COLOUR_GOLD    = 0xF0B429
COLOUR_GREEN   = 0x00C853
COLOUR_RED     = 0xFF1744
COLOUR_BLUE    = 0x2979FF
COLOUR_PURPLE  = 0x7C4DFF

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix="!", intents=intents)
anthropic_client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

current_portfolio = None


def sector_emoji(sector: str) -> str:
    mapping = {
        "Technology": "💻", "Healthcare": "🏥", "Financial Services": "🏦",
        "Consumer Cyclical": "🛍️", "Consumer Defensive": "🛒",
        "Energy": "⚡", "Industrials": "🏭", "Communication Services": "📡",
        "Real Estate": "🏢", "Basic Materials": "⛏️", "Utilities": "💡",
    }
    return mapping.get(sector, "📈")


def allocation_bar(pct: float) -> str:
    filled = round(pct / 10)
    return "█" * filled + "░" * (10 - filled)


async def post_portfolio(channel, portfolio):
    stocks = portfolio.get("picks", [])
    date_str = portfolio.get("date", datetime.now().strftime("%d %b %Y"))
    name = portfolio.get("portfolio_name", "Lee's AI Portfolio")
    thesis = portfolio.get("summary", "")

    header = discord.Embed(title=f"🤖 {name}", description=f"*{thesis}*", colour=COLOUR_GOLD, timestamp=datetime.now())
    header.add_field(name="📅 Date", value=date_str, inline=True)
    header.add_field(name="📊 Holdings", value=f"{len(stocks)} stocks", inline=True)
    header.add_field(name="🔁 Rebalance", value="Weekly (Monday)", inline=True)
    header.set_footer(text="Lee's AI Portfolio Bot • Not financial advice")
    await channel.send(embed=header)
    await asyncio.sleep(0.5)

    alloc_lines = []
    for s in sorted(stocks, key=lambda x: x.get("allocation", 0), reverse=True):
        bar = allocation_bar(s["allocation"])
        emoji = sector_emoji(s.get("sector", ""))
        alloc_lines.append(f"{emoji} **${s['ticker']}** {bar} `{s['allocation']}%`")

    alloc_embed = discord.Embed(title="📊 Portfolio Allocation", description="\n".join(alloc_lines), colour=COLOUR_BLUE)
    await channel.send(embed=alloc_embed)
    await asyncio.sleep(0.5)

    for i in range(0, len(stocks), 2):
        chunk = stocks[i:i+2]
        embed = discord.Embed(colour=COLOUR_PURPLE)
        for s in chunk:
            ticker = s["ticker"]
            alloc = s["allocation"]
            price = s.get("current_price", "N/A")
            target = s.get("analyst_target")
            score = s.get("score", "N/A")
            bull = s.get("bull_case", "N/A")
            bear = s.get("bear_risk", "N/A")
            emoji = sector_emoji(s.get("sector", ""))
            upside_str = ""
            if target and price and price != "N/A":
                try:
                    upside = ((float(target) - float(price)) / float(price)) * 100
                    upside_str = f" → **${target:.0f}** `+{upside:.0f}%`" if upside > 0 else f" → **${target:.0f}** `{upside:.0f}%`"
                except:
                    pass
            field_val = (f"{emoji} **{s.get('name', ticker)}** — `{alloc}%` allocation\n"
                        f"💰 Price: **${price}**{upside_str}\n🎯 AI Score: **{score}/100**\n"
                        f"🟢 **Bull:** {bull}\n🔴 **Bear:** {bear}")
            embed.add_field(name=f"${ticker}", value=field_val, inline=False)
        await channel.send(embed=embed)
        await asyncio.sleep(0.5)

    footer_embed = discord.Embed(title="⚠️ Disclaimer",
        description="This portfolio is generated by AI for **informational purposes only**.\nIt is **not financial advice**. Always do your own research before investing.",
        colour=COLOUR_RED)
    footer_embed.set_footer(text="Lee's AI Portfolio Bot • Powered by Claude + Yahoo Finance")
    await channel.send(embed=footer_embed)


async def run_portfolio_update(channel):
    global current_portfolio
    status_msg = await channel.send("🔄 **Running portfolio analysis...** Stand by.")
    try:
        loop = asyncio.get_event_loop()
        portfolio = await loop.run_in_executor(None, lambda: build_portfolio(anthropic_client, None))
        current_portfolio = portfolio
        await status_msg.edit(content="✅ **Analysis complete! Posting portfolio...**")
        await asyncio.sleep(1)
        await status_msg.delete()
        await post_portfolio(channel, portfolio)
    except Exception as e:
        await status_msg.edit(content=f"❌ **Error running analysis:** `{str(e)}`")


@bot.event
async def on_ready():
    print(f"✅ {bot.user} is online")
    channel = bot.get_channel(CHANNEL_ID)
    if channel:
        await channel.send("🤖 **Lee's AI Stock Portfolio Bot is online!**\nCommands: `!portfolio` — run now | `!holdings` — current picks | `!analyse TSLA` — single stock\nAuto-rebalance: every **Monday 8am**.")
    weekly_rebalance.start()


@bot.command(name="portfolio")
async def cmd_portfolio(ctx):
    channel = bot.get_channel(CHANNEL_ID) or ctx.channel
    await run_portfolio_update(channel)


@bot.command(name="holdings")
async def cmd_holdings(ctx):
    if not current_portfolio:
        await ctx.send("❌ No portfolio yet. Run `!portfolio` first.")
        return
    stocks = current_portfolio.get("picks", [])
    lines = [f"{sector_emoji(s.get('sector',''))} **${s['ticker']}** — `{s['allocation']}%` | Score: {s.get('score','N/A')}"
             for s in sorted(stocks, key=lambda x: x["allocation"], reverse=True)]
    embed = discord.Embed(title="📋 Current Portfolio", description="\n".join(lines), colour=COLOUR_GOLD, timestamp=datetime.now())
    embed.set_footer(text=f"Generated: {current_portfolio.get('date','Unknown')}")
    await ctx.send(embed=embed)


@bot.command(name="analyse")
async def cmd_analyse(ctx, ticker: str):
    ticker = ticker.upper()
    msg = await ctx.send(f"🔍 Analysing **${ticker}**...")
    from stock_engine import fetch_stock_data, score_stock
    loop = asyncio.get_event_loop()
    data = await loop.run_in_executor(None, lambda: fetch_stock_data(ticker))
    if not data:
        await msg.edit(content=f"❌ Could not fetch data for **${ticker}**.")
        return
    score = score_stock(data)
    prompt = f"""Give a brief 3-sentence analysis of {ticker} ({data.get('name')}) as a stock pick today.
Data: Price ${data.get('price')}, Forward PE {data.get('forward_pe')}, 1-month momentum {data.get('momentum_1mo')}%, earnings growth {data.get('earnings_growth')}, analyst recommendation: {data.get('recommendation')}, analyst target: ${data.get('analyst_target')}.
Format: One sentence bull case. One sentence bear risk. One sentence verdict (BUY/HOLD/AVOID)."""
    response = anthropic_client.messages.create(model="claude-opus-4-6", max_tokens=200, messages=[{"role":"user","content":prompt}])
    ai_take = response.content[0].text.strip()
    embed = discord.Embed(title=f"🔍 ${ticker} — Quick Analysis", colour=COLOUR_GREEN if score >= 60 else (COLOUR_GOLD if score >= 45 else COLOUR_RED))
    embed.add_field(name="Company", value=data.get("name", ticker), inline=True)
    embed.add_field(name="Sector", value=data.get("sector","N/A"), inline=True)
    embed.add_field(name="AI Score", value=f"**{score}/100**", inline=True)
    embed.add_field(name="Price", value=f"${data.get('price')}", inline=True)
    embed.add_field(name="1mo Momentum", value=f"{data.get('momentum_1mo')}%", inline=True)
    embed.add_field(name="Analyst Target", value=f"${data.get('analyst_target','N/A')}", inline=True)
    embed.add_field(name="🤖 AI Take", value=ai_take, inline=False)
    embed.set_footer(text="Not financial advice")
    await msg.delete()
    await ctx.send(embed=embed)


@tasks.loop(hours=168)
async def weekly_rebalance():
    if datetime.now().weekday() == 0:
        channel = bot.get_channel(CHANNEL_ID)
        if channel:
            await channel.send("📅 **Weekly rebalance triggered!**")
            await run_portfolio_update(channel)


@weekly_rebalance.before_loop
async def before_rebalance():
    await bot.wait_until_ready()


if __name__ == "__main__":
    bot.run(DISCORD_TOKEN)
